// Generated by Wrangler by running `wrangler types`

interface Env {
	contracting_estimates: KVNamespace;
	BE_TEST: Service<import("be-rpc-estimates/src/index").default>;
	BE_TEST_112: Service<import("be-rpc-estimates/src/index").Testes>;
	BE_TEST_ZIP_METHODS: Service<import("be-rpc-estimates/src/index").Zips>;
}
