// Generated by Wrangler by running `wrangler types`

interface Env {
	contracting_estimates: KVNamespace;
	ZIP_METHODS: Service<import("be-rpc-estimates/src/index").Zips>;
	DB: Service<import("be-rpc-estimates/src/index").D1Worker>;
}
