#:schema node_modules/wrangler/config-schema.json
name = "zach-estimates-astro-24"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "contracting_estimates"
id = "f460e30034dc4dd8b2a9389029785431"

[[services]]
binding = "ZIP_METHODS"
service = "be-rpc-estimates"
entrypoint = "Zips"

[[services]]
binding = "DB"
service = "be-rpc-estimates"
entrypoint = "D1Worker"