/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./schemas";
export type Json = z.infer<typeof generated.jsonSchema>;
export type GraphqlPublicGraphqlArgsSchema = z.infer<
  typeof generated.graphqlPublicGraphqlArgsSchemaSchema
>;
export type GraphqlPublicGraphqlReturnsSchema = z.infer<
  typeof generated.graphqlPublicGraphqlReturnsSchemaSchema
>;
export type PublicAdPlatformDataRowSchema = z.infer<
  typeof generated.publicAdPlatformDataRowSchemaSchema
>;
export type PublicAdPlatformDataInsertSchema = z.infer<
  typeof generated.publicAdPlatformDataInsertSchemaSchema
>;
export type PublicAdPlatformDataUpdateSchema = z.infer<
  typeof generated.publicAdPlatformDataUpdateSchemaSchema
>;
export type PublicAlertConfigurationsRowSchema = z.infer<
  typeof generated.publicAlertConfigurationsRowSchemaSchema
>;
export type PublicAlertConfigurationsInsertSchema = z.infer<
  typeof generated.publicAlertConfigurationsInsertSchemaSchema
>;
export type PublicAlertConfigurationsUpdateSchema = z.infer<
  typeof generated.publicAlertConfigurationsUpdateSchemaSchema
>;
export type PublicBuyerZipCodesRowSchema = z.infer<
  typeof generated.publicBuyerZipCodesRowSchemaSchema
>;
export type PublicBuyerZipCodesInsertSchema = z.infer<
  typeof generated.publicBuyerZipCodesInsertSchemaSchema
>;
export type PublicBuyerZipCodesUpdateSchema = z.infer<
  typeof generated.publicBuyerZipCodesUpdateSchemaSchema
>;
export type PublicBuyerZipCodesRelationshipsSchema = z.infer<
  typeof generated.publicBuyerZipCodesRelationshipsSchemaSchema
>;
export type PublicBuyersRowSchema = z.infer<
  typeof generated.publicBuyersRowSchemaSchema
>;
export type PublicBuyersInsertSchema = z.infer<
  typeof generated.publicBuyersInsertSchemaSchema
>;
export type PublicBuyersUpdateSchema = z.infer<
  typeof generated.publicBuyersUpdateSchemaSchema
>;
export type PublicLeadDispositionsRowSchema = z.infer<
  typeof generated.publicLeadDispositionsRowSchemaSchema
>;
export type PublicLeadDispositionsInsertSchema = z.infer<
  typeof generated.publicLeadDispositionsInsertSchemaSchema
>;
export type PublicLeadDispositionsUpdateSchema = z.infer<
  typeof generated.publicLeadDispositionsUpdateSchemaSchema
>;
export type PublicLeadDispositionsRelationshipsSchema = z.infer<
  typeof generated.publicLeadDispositionsRelationshipsSchemaSchema
>;
export type PublicLeadsRowSchema = z.infer<
  typeof generated.publicLeadsRowSchemaSchema
>;
export type PublicLeadsInsertSchema = z.infer<
  typeof generated.publicLeadsInsertSchemaSchema
>;
export type PublicLeadsUpdateSchema = z.infer<
  typeof generated.publicLeadsUpdateSchemaSchema
>;
export type PublicLeadsRelationshipsSchema = z.infer<
  typeof generated.publicLeadsRelationshipsSchemaSchema
>;
export type PublicOfflineConversionsRowSchema = z.infer<
  typeof generated.publicOfflineConversionsRowSchemaSchema
>;
export type PublicOfflineConversionsInsertSchema = z.infer<
  typeof generated.publicOfflineConversionsInsertSchemaSchema
>;
export type PublicOfflineConversionsUpdateSchema = z.infer<
  typeof generated.publicOfflineConversionsUpdateSchemaSchema
>;
export type PublicOfflineConversionsRelationshipsSchema = z.infer<
  typeof generated.publicOfflineConversionsRelationshipsSchemaSchema
>;
export type PublicZipCodePopulationsRowSchema = z.infer<
  typeof generated.publicZipCodePopulationsRowSchemaSchema
>;
export type PublicZipCodePopulationsInsertSchema = z.infer<
  typeof generated.publicZipCodePopulationsInsertSchemaSchema
>;
export type PublicZipCodePopulationsUpdateSchema = z.infer<
  typeof generated.publicZipCodePopulationsUpdateSchemaSchema
>;
